config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "welcome/say_hello"=>"welcome#say"
  get "welcome"=>"welcome#index"
  root "welcome#index"







  match ':controller(/:action(/:id(.:format)))',:via=>:all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events=Event.all
  end
  def new
    @event=Event.new()
  end
  def update
    @event=Event.find(params[:id])
    @event.update(event_params)
    redirect_to :action=>:show,:id=>@event
  end
  def create
    @event=Event.new(event_params)
    @event.save
    redirect_to :action=>:index
  end
  def show
    @event=Event.find(params[:id])
  end
  def edit
    @event=Event.find(params[:id])
  end
  def destroy
    @event=Event.find(params[:id])
    @event.destroy
    redirect_to :action=>:index
  end
  private
  def event_params
    params.require(:event).permit(:name,:description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say
  end
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<%= form_for @event,:url=>{:controller=>'events',:action=>'update',:id=>@event} do |f|%>
<%= f.label :name,"Name"%>
<%= f.text_field :name%>
<%= f.label :description, "Description" %>
    <%= f.text_area :description %>
<%= f.submit "update"%>
<% end%>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ul>
      <% @events.each do |event| %>
      <li><%=  event.name %>
      <%= link_to 'Show', :controller => 'events', :action => 'show', :id => event %>
  <%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
  <%= link_to 'Delete', :controller => 'events', :action => 'destroy', :id => event %>
  </li>
      <% end %>

    </ul>
    <%= link_to 'new Event',:controller=>'events',:action=>'new'%>
  </body>
</html>

app/views/events/new.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'create' } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name%>
<%= simple_format(@event.description)%>
<p><%= link_to 'back to index', :controller=>'events',:action=>'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<p>hola! It's <%= Time.now%></p>
<p><%= link_to 'hello',welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>hello world</h1>